### ISSUE TITLE
Any plans for further development?

### ISSUE THREAD

**Issue by redzioch** [camptocamp/terraform-provider-freeipa#20]
Do you have any plans for further development? It would be superb if we can have resources to manage user groups, host groups, rules etc.

**Comment by KingKeithC** [comment]
+1

**Comment by mcanevet** [comment]
We currently have no need for other resources in this provider so unless we find some way to finance this effort, we'll not do it ourselves. But as this is Open Source software, we'd gladly accept external contributions.
